services:
  mysql:
    image: mysql:latest
    container_name: challenge-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
    ports:
      - '3306:3306'
